name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the analysis on
  pull_request:
    branches:
      - main  # Adjust this to the branch you want to trigger the analysis on

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package  # Replace this with your build command

      - name: Download SonarScanner
        run: |
          curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip

      - name: Configure SonarQube properties
        run: |
          echo "sonar.host.url=<YOUR_SONARQUBE_SERVER_URL>" >> sonar-scanner-4.7.0.2747-linux/conf/sonar-scanner.properties
          echo "sonar.login=<YOUR_SONARQUBE_ACCESS_TOKEN>" >> sonar-scanner-4.7.0.2747-linux/conf/sonar-scanner.properties
          # Add any additional SonarQube properties you need

      - name: Run SonarScanner analysis
        run: sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner
